// generated by build_data.py — do not edit
export const KE_DATA = {
 "meta": {
  "kind": "concept",
  "source": "arXiv:1706.03762",
  "generated": "2026-07-08",
  "version": 1
 },
 "nodes": [
  {
   "id": "transformer",
   "kind": "concept",
   "label": "The Transformer",
   "level": 0,
   "page": "01_transformer.md",
   "anchor": "#tldr",
   "source_ref": "sec:1"
  },
  {
   "id": "encoder-decoder-stack",
   "kind": "concept",
   "label": "Encoder–Decoder Stack",
   "level": 1,
   "source_ref": "sec:3.1"
  },
  {
   "id": "attention",
   "kind": "concept",
   "label": "Attention",
   "level": 1,
   "page": "03_attention.md",
   "anchor": "#intuition",
   "source_ref": "sec:3.2"
  },
  {
   "id": "positional-encoding",
   "kind": "concept",
   "label": "Positional Encoding",
   "level": 1,
   "source_ref": "sec:3.5"
  },
  {
   "id": "why-self-attention",
   "kind": "concept",
   "label": "Why Self-Attention?",
   "level": 1,
   "source_ref": "sec:4"
  },
  {
   "id": "scaled-dot-product-attention",
   "kind": "concept",
   "label": "Scaled Dot-Product Attention",
   "level": 2,
   "page": "04_sdpa.md",
   "anchor": "#mechanics",
   "source_ref": "sec:3.2.1"
  },
  {
   "id": "multi-head-attention",
   "kind": "concept",
   "label": "Multi-Head Attention",
   "level": 2,
   "source_ref": "sec:3.2.2"
  },
  {
   "id": "feed-forward-network",
   "kind": "concept",
   "label": "Position-wise Feed-Forward",
   "level": 2,
   "source_ref": "sec:3.3"
  },
  {
   "id": "residual-layer-norm",
   "kind": "concept",
   "label": "Residuals + LayerNorm",
   "level": 2,
   "source_ref": "sec:3.1"
  },
  {
   "id": "attention-equation",
   "kind": "equation",
   "label": "Attention(Q,K,V) = softmax(QKᵀ/√dₖ)V",
   "level": 3,
   "source_ref": "eq:1"
  },
  {
   "id": "sqrt-dk-scaling",
   "kind": "concept",
   "label": "The √dₖ Scaling",
   "level": 3,
   "source_ref": "sec:3.2.1"
  }
 ],
 "edges": [
  {
   "src": "encoder-decoder-stack",
   "dst": "transformer",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "attention",
   "dst": "transformer",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "positional-encoding",
   "dst": "transformer",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "why-self-attention",
   "dst": "transformer",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "scaled-dot-product-attention",
   "dst": "attention",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "multi-head-attention",
   "dst": "attention",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "feed-forward-network",
   "dst": "encoder-decoder-stack",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "residual-layer-norm",
   "dst": "encoder-decoder-stack",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "attention-equation",
   "dst": "scaled-dot-product-attention",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "sqrt-dk-scaling",
   "dst": "scaled-dot-product-attention",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "multi-head-attention",
   "dst": "scaled-dot-product-attention",
   "kind": "builds-on",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "attention",
   "dst": "why-self-attention",
   "kind": "prerequisite",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  }
 ],
 "pages": {},
 "notes": {},
 "hotspots": [],
 "clusters": [
  {
   "id": "encoder-decoder-stack",
   "label": "Encoder–Decoder Stack",
   "nodeIds": [
    "encoder-decoder-stack",
    "feed-forward-network",
    "residual-layer-norm"
   ]
  },
  {
   "id": "attention",
   "label": "Attention",
   "nodeIds": [
    "attention",
    "attention-equation",
    "multi-head-attention",
    "scaled-dot-product-attention",
    "sqrt-dk-scaling"
   ]
  },
  {
   "id": "positional-encoding",
   "label": "Positional Encoding",
   "nodeIds": [
    "positional-encoding"
   ]
  },
  {
   "id": "why-self-attention",
   "label": "Why Self-Attention?",
   "nodeIds": [
    "why-self-attention"
   ]
  }
 ],
 "tour": [
  {
   "order": 1,
   "title": "The Transformer",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "transformer"
   ]
  },
  {
   "order": 2,
   "title": "Attention",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "attention"
   ]
  },
  {
   "order": 3,
   "title": "Encoder–Decoder Stack",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "encoder-decoder-stack"
   ]
  },
  {
   "order": 4,
   "title": "Positional Encoding",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "positional-encoding"
   ]
  },
  {
   "order": 5,
   "title": "Why Self-Attention?",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "why-self-attention"
   ]
  }
 ],
 "provenance": {},
 "centrality": {
  "transformer": 0.0,
  "encoder-decoder-stack": 0.0222,
  "attention": 0.0889,
  "positional-encoding": 0.0,
  "why-self-attention": 0.0,
  "scaled-dot-product-attention": 0.0667,
  "multi-head-attention": 0.0,
  "feed-forward-network": 0.0,
  "residual-layer-norm": 0.0,
  "attention-equation": 0.0,
  "sqrt-dk-scaling": 0.0
 },
 "eqIndex": {},
 "trace": [],
 "glossary": {},
 "dependentSide": {
  "part-of": "dst",
  "prerequisite": "dst",
  "builds-on": "src"
 }
};
