// generated by build_data.py — do not edit
export const KE_DATA = {
 "meta": {
  "kind": "concept",
  "source": "arXiv:1706.03762",
  "generated": "2026-07-08",
  "version": 1
 },
 "nodes": [
  {
   "id": "transformer",
   "kind": "concept",
   "label": "The Transformer",
   "level": 0,
   "page": "01_transformer.md",
   "anchor": "#tldr",
   "source_ref": "sec:1"
  },
  {
   "id": "encoder-decoder-stack",
   "kind": "concept",
   "label": "Encoder–Decoder Stack",
   "level": 1,
   "source_ref": "sec:3.1"
  },
  {
   "id": "attention",
   "kind": "concept",
   "label": "Attention",
   "level": 1,
   "page": "03_attention.md",
   "anchor": "#intuition",
   "source_ref": "sec:3.2"
  },
  {
   "id": "positional-encoding",
   "kind": "concept",
   "label": "Positional Encoding",
   "level": 1,
   "source_ref": "sec:3.5"
  },
  {
   "id": "why-self-attention",
   "kind": "concept",
   "label": "Why Self-Attention?",
   "level": 1,
   "source_ref": "sec:4"
  },
  {
   "id": "scaled-dot-product-attention",
   "kind": "concept",
   "label": "Scaled Dot-Product Attention",
   "level": 2,
   "page": "04_sdpa.md",
   "anchor": "#mechanics",
   "source_ref": "sec:3.2.1"
  },
  {
   "id": "multi-head-attention",
   "kind": "concept",
   "label": "Multi-Head Attention",
   "level": 2,
   "source_ref": "sec:3.2.2"
  },
  {
   "id": "feed-forward-network",
   "kind": "concept",
   "label": "Position-wise Feed-Forward",
   "level": 2,
   "source_ref": "sec:3.3"
  },
  {
   "id": "residual-layer-norm",
   "kind": "concept",
   "label": "Residuals + LayerNorm",
   "level": 2,
   "source_ref": "sec:3.1"
  },
  {
   "id": "attention-equation",
   "kind": "equation",
   "label": "Attention(Q,K,V) = softmax(QKᵀ/√dₖ)V",
   "level": 3,
   "source_ref": "eq:1"
  },
  {
   "id": "sqrt-dk-scaling",
   "kind": "concept",
   "label": "The √dₖ Scaling",
   "level": 3,
   "source_ref": "sec:3.2.1"
  }
 ],
 "edges": [
  {
   "src": "encoder-decoder-stack",
   "dst": "transformer",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "attention",
   "dst": "transformer",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "positional-encoding",
   "dst": "transformer",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "why-self-attention",
   "dst": "transformer",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "scaled-dot-product-attention",
   "dst": "attention",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "multi-head-attention",
   "dst": "attention",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "feed-forward-network",
   "dst": "encoder-decoder-stack",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "residual-layer-norm",
   "dst": "encoder-decoder-stack",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "attention-equation",
   "dst": "scaled-dot-product-attention",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "sqrt-dk-scaling",
   "dst": "scaled-dot-product-attention",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "multi-head-attention",
   "dst": "scaled-dot-product-attention",
   "kind": "builds-on",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  },
  {
   "src": "attention",
   "dst": "why-self-attention",
   "kind": "prerequisite",
   "weight": 1.0,
   "confidence": "extracted",
   "confidence_score": 1.0
  }
 ],
 "pages": {
  "sdpa": "# Scaled Dot-Product Attention\n\n## TL;DR {#tldr}\n\nScaled dot-product attention compares each query Q with keys K, scales the scores, and uses them to mix values V.\n\n## Intuition {#intuition}\n\nThink of softmax as a relevance dial: similar keys receive more of the available attention.\n\n## Mechanics {#mechanics}\n\nCompute query-key scores, divide by the key dimension scale, apply softmax, and multiply by V.\n\n## The Math {#the-math}\n\n$$\\operatorname{Attention}(Q,K,V)=\\operatorname{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V$$\n\nThe factor \\(\\sqrt{d_k}\\) keeps large dot products from saturating softmax.\n\n## Go Deeper {#go-deeper}\n\nEquation eq_1 anchors the scaling operation to the graph nodes that explain it.\n"
 },
 "notes": {
  "scaled-dot-product-attention": {
   "concept": "scaled-dot-product-attention",
   "status": "verified",
   "date": "2026-07-08",
   "synthesis": "Scaled dot-product attention uses softmax over scaled query-key scores.",
   "glossary": {
    "Q": "Query vectors used to request relevant information.",
    "K": "Key vectors compared with each query.",
    "V": "Value vectors blended by the attention weights.",
    "softmax": "A normalized exponential distribution over scores."
   }
  }
 },
 "hotspots": [],
 "clusters": [
  {
   "id": "encoder-decoder-stack",
   "label": "Encoder–Decoder Stack",
   "nodeIds": [
    "encoder-decoder-stack",
    "feed-forward-network",
    "residual-layer-norm"
   ]
  },
  {
   "id": "attention",
   "label": "Attention",
   "nodeIds": [
    "attention",
    "attention-equation",
    "multi-head-attention",
    "scaled-dot-product-attention",
    "sqrt-dk-scaling"
   ]
  },
  {
   "id": "positional-encoding",
   "label": "Positional Encoding",
   "nodeIds": [
    "positional-encoding"
   ]
  },
  {
   "id": "why-self-attention",
   "label": "Why Self-Attention?",
   "nodeIds": [
    "why-self-attention"
   ]
  }
 ],
 "tour": [
  {
   "order": 1,
   "title": "The Transformer",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "transformer"
   ]
  },
  {
   "order": 2,
   "title": "Attention",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "attention"
   ]
  },
  {
   "order": 3,
   "title": "Encoder–Decoder Stack",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "encoder-decoder-stack"
   ]
  },
  {
   "order": 4,
   "title": "Positional Encoding",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "positional-encoding"
   ]
  },
  {
   "order": 5,
   "title": "Why Self-Attention?",
   "description": "Next stop on the dependency-ordered reading path.",
   "nodeIds": [
    "why-self-attention"
   ]
  }
 ],
 "provenance": {
  "path": "latex",
  "equation_fidelity": "exact"
 },
 "centrality": {
  "transformer": 0.0,
  "encoder-decoder-stack": 0.0222,
  "attention": 0.0889,
  "positional-encoding": 0.0,
  "why-self-attention": 0.0,
  "scaled-dot-product-attention": 0.0667,
  "multi-head-attention": 0.0,
  "feed-forward-network": 0.0,
  "residual-layer-norm": 0.0,
  "attention-equation": 0.0,
  "sqrt-dk-scaling": 0.0
 },
 "eqIndex": {
  "eq_1": [
   "scaled-dot-product-attention",
   "sqrt-dk-scaling"
  ]
 },
 "trace": [
  {
   "nodeId": "scaled-dot-product-attention",
   "phase": "researched",
   "status": "verified",
   "date": "2026-07-08"
  },
  {
   "nodeId": "scaled-dot-product-attention",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-08"
  }
 ],
 "glossary": {
  "scaled-dot-product-attention": {
   "Q": "Query vectors used to request relevant information.",
   "K": "Key vectors compared with each query.",
   "V": "Value vectors blended by the attention weights.",
   "softmax": "A normalized exponential distribution over scores."
  }
 },
 "excerpts": {},
 "dependentSide": {
  "part-of": "dst",
  "prerequisite": "dst",
  "builds-on": "src"
 }
};
