// generated by build_data.py — do not edit
export const KE_DATA = {
 "meta": {
  "kind": "concept",
  "source": "file:C:\\Users\\Rp\\OneDrive\\Desktop\\Fall 2025\\EE456\\2205.06900v2 (2).pdf",
  "generated": "2026-07-17",
  "version": 1,
  "model": "gpt-5.6-luna"
 },
 "nodes": [
  {
   "id": "universal-post-training-backdoor-detection",
   "kind": "concept",
   "level": 0,
   "source_ref": "sec_1",
   "label": "Universal Post-Training Backdoor Detection (MM-BD)"
  },
  {
   "id": "backdoor-threat-model",
   "kind": "concept",
   "level": 1,
   "source_ref": "sec_1",
   "label": "Backdoor Threat Model"
  },
  {
   "id": "post-training-defender-constraints",
   "kind": "concept",
   "level": 1,
   "source_ref": "sec_1",
   "label": "Post-Training Defender Constraints"
  },
  {
   "id": "logit-output-landscape",
   "kind": "concept",
   "level": 1,
   "source_ref": "sec_1",
   "label": "Pre-Softmax Logit Landscape"
  },
  {
   "id": "pattern-agnostic-signature",
   "kind": "concept",
   "level": 1,
   "source_ref": "sec_1",
   "label": "Pattern-Agnostic Attack Signature"
  },
  {
   "id": "maximum-margin-objective",
   "kind": "concept",
   "level": 1,
   "source_ref": "sec_1",
   "label": "Maximum-Margin Objective"
  },
  {
   "id": "unsupervised-anomaly-inference",
   "kind": "concept",
   "level": 1,
   "source_ref": "sec_1",
   "label": "Unsupervised Anomaly Inference"
  },
  {
   "id": "activation-bound-mitigation",
   "kind": "concept",
   "level": 1,
   "source_ref": "sec_1",
   "label": "Maximum-Margin Backdoor Mitigation (MM-BM)"
  },
  {
   "id": "classical-poisoning-mechanism",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Classical Poisoning Mechanism"
  },
  {
   "id": "trigger-embedding-families",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Trigger-Embedding Families"
  },
  {
   "id": "attacker-capability-ladder",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Basic, Advanced, and Adaptive Attackers"
  },
  {
   "id": "clean-data-free-estimation",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Clean-Data-Free Estimation"
  },
  {
   "id": "boosting-and-suppression",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Target-Logit Boosting and Non-Target Suppression"
  },
  {
   "id": "projected-gradient-estimation",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Projected Gradient Estimation"
  },
  {
   "id": "null-margin-distribution",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Null Distribution of Class Margins"
  },
  {
   "id": "order-statistic-pvalue",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Order-Statistic p-Value"
  },
  {
   "id": "adaptive-attack-minimax",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Adaptive Min-Max Attack"
  },
  {
   "id": "per-neuron-upper-bounds",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Per-Neuron Activation Upper Bounds"
  },
  {
   "id": "accuracy-preserving-lagrangian",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Accuracy-Preserving Lagrangian"
  },
  {
   "id": "empirical-scope-and-limitations",
   "kind": "concept",
   "level": 2,
   "source_ref": "sec_1",
   "label": "Empirical Scope and Failure Modes"
  }
 ],
 "edges": [
  {
   "src": "backdoor-threat-model",
   "dst": "universal-post-training-backdoor-detection",
   "kind": "prerequisite",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "post-training-defender-constraints",
   "dst": "universal-post-training-backdoor-detection",
   "kind": "prerequisite",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "logit-output-landscape",
   "dst": "universal-post-training-backdoor-detection",
   "kind": "prerequisite",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "maximum-margin-objective",
   "dst": "universal-post-training-backdoor-detection",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "unsupervised-anomaly-inference",
   "dst": "universal-post-training-backdoor-detection",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "activation-bound-mitigation",
   "dst": "universal-post-training-backdoor-detection",
   "kind": "builds-on",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.9
  },
  {
   "src": "classical-poisoning-mechanism",
   "dst": "backdoor-threat-model",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "trigger-embedding-families",
   "dst": "backdoor-threat-model",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "attacker-capability-ladder",
   "dst": "backdoor-threat-model",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "pattern-agnostic-signature",
   "dst": "logit-output-landscape",
   "kind": "builds-on",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "boosting-and-suppression",
   "dst": "pattern-agnostic-signature",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.9
  },
  {
   "src": "clean-data-free-estimation",
   "dst": "maximum-margin-objective",
   "kind": "builds-on",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "projected-gradient-estimation",
   "dst": "maximum-margin-objective",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "null-margin-distribution",
   "dst": "unsupervised-anomaly-inference",
   "kind": "prerequisite",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "order-statistic-pvalue",
   "dst": "unsupervised-anomaly-inference",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "maximum-margin-objective",
   "dst": "unsupervised-anomaly-inference",
   "kind": "prerequisite",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "adaptive-attack-minimax",
   "dst": "attacker-capability-ladder",
   "kind": "builds-on",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.9
  },
  {
   "src": "per-neuron-upper-bounds",
   "dst": "activation-bound-mitigation",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "accuracy-preserving-lagrangian",
   "dst": "activation-bound-mitigation",
   "kind": "part-of",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.95
  },
  {
   "src": "empirical-scope-and-limitations",
   "dst": "universal-post-training-backdoor-detection",
   "kind": "contrasts-with",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.9
  },
  {
   "src": "empirical-scope-and-limitations",
   "dst": "unsupervised-anomaly-inference",
   "kind": "builds-on",
   "weight": 1.0,
   "confidence": "paper",
   "confidence_score": 0.85
  }
 ],
 "pages": {
  "backdoor-threat-model": "# Backdoor Threat Model\n\n## TL;DR {#tldr}\nThe paper studies a trained image classifier that behaves normally on clean inputs but routes triggered inputs from one or more source classes to an attacker-chosen target class.\n\n## Intuition {#intuition}\nThe attack is like hiding a secret instruction in a model's training history. A normal image should be recognized by its ordinary content, but the same small cue repeated during poisoning becomes a shortcut that overrides that content later.\n\n## Mechanics {#mechanics}\nThe paper distinguishes basic, advanced, and adaptive attackers. The basic attacker poisons data without seeing the original training set or controlling training; advanced attackers may use surrogate data or training control; an adaptive attacker also knows MM-BD and optimizes against it [§sec_1]. The defender receives a trained classifier after training and wants detection first, followed by mitigation if replacement is unavailable [§sec_1].\n\n## The Math {#the-math}\nA classical backdoor aims for clean correctness and triggered misclassification simultaneously: $$f(\\mathbf{x})=y_{\\mathrm{true}},\\qquad f(\\tilde{\\mathbf{x}})=t$$ [§sec_1]. The paper's threat model makes $t$ an attacker-selected target and allows an arbitrary number of source classes [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Classical Poisoning Mechanism gives the training-time construction.\n- Attacker Capability Ladder compares the three attacker regimes.\n- Empirical Scope and Failure Modes records where the assumptions become fragile.\n",
  "maximum-margin-objective": "# Maximum-Margin Objective\n\n## TL;DR {#tldr}\nFor every class, MM-BD maximizes the gap between that class's logit and the largest competing logit over valid inputs.\n\n## Intuition {#intuition}\nInstead of asking whether a class can shout loudly, ask whether it can shout while silencing the loudest rival. That contest is harder for ordinary neighboring classes and becomes conspicuous when a backdoor target has learned an over-specialized route.\n\n## Mechanics {#mechanics}\nThe estimation stage solves one optimization problem per class. It uses the full input domain as the search space, performs multiple random starts, and keeps the largest local optimum found for that class [§sec_1]. The resulting $r_c$ values are the only model-derived features needed by the unsupervised detector [§sec_1].\n\n## The Math {#the-math}\nThe core program is $$\\underset{\\mathbf{x}\\in\\mathcal{X}}{\\operatorname{maximize}}\\;g_c(\\mathbf{x})-\\max_{k\\in\\mathcal{Y}\\setminus\\{c\\}}g_k(\\mathbf{x})$$ [§sec_1]. Comparing against the maximum rival makes the statistic robust to classes whose logits rise together, a failure mode the paper illustrates for logit-only alternatives [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Projected Gradient Estimation explains the numerical solver.\n- Null Distribution of Class Margins consumes one statistic per class.\n- Order-Statistic p-Value converts the maximum into a decision.\n",
  "post-training-defender-constraints": "# Post-Training Defender Constraints\n\n## TL;DR {#tldr}\nMM-BD is designed for a downstream user who has the trained classifier but no training set, no known trigger, and no clean reference classifier.\n\n## Intuition {#intuition}\nThis is an inspection problem, not a retraining problem. The defender has the finished artifact and must decide whether its behavior contains a hidden route, even when the evidence used to build the route is gone or proprietary.\n\n## Mechanics {#mechanics}\nThe paper lists five assumptions: the defender does not know whether an attack exists, does not know the pattern type, lacks the training set, lacks a clean classifier for comparison, and may not possess clean examples. MM-BD needs no clean samples for detection, although MM-BM later uses a small clean set for accuracy preservation [§sec_1].\n\n## The Math {#the-math}\nThe detection input is the model itself: $g_c(\\cdot)$ is queried over the input domain $\\mathcal{X}$, while the clean sample set $D$ appears only in the mitigation problem [§sec_1]. This separation is the reason the detector can be data-free at inference time [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Clean-Data-Free Estimation shows how random inputs replace a reference dataset.\n- Unsupervised Anomaly Inference shows how a decision is made without labels.\n- Accuracy-Preserving Lagrangian explains the extra data needed for repair.\n",
  "logit-output-landscape": "# Pre-Softmax Logit Landscape\n\n## TL;DR {#tldr}\nThe logit landscape is the set of class score functions before softmax; MM-BD searches this landscape because a backdoor changes its geometry before probabilities are normalized.\n\n## Intuition {#intuition}\nSoftmax is a translator that turns scores into probabilities. MM-BD listens to the raw voices before translation, where it can compare how far one class can rise above all others rather than being distracted by normalization.\n\n## Mechanics {#mechanics}\nLet $g_c(\\mathbf{x})$ be the logit for class $c$. For every candidate class, MM-BD asks how large the gap to the strongest rival can become over valid inputs. A backdoor repeats a common feature during poisoning, so the target's score surface can acquire a sharper, more reusable direction than ordinary class evidence [§sec_1].\n\n## The Math {#the-math}\nThe class margin at an input is $$m_c(\\mathbf{x})=g_c(\\mathbf{x})-\\max_{k\\ne c}g_k(\\mathbf{x})$$ [§sec_1]. The landscape statistic is the supremum of this margin over $\\mathcal{X}$, so it measures separability from the strongest competitor rather than the absolute value of one logit [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Maximum-Margin Objective turns the landscape into a statistic.\n- Boosting and Suppression explains the backdoor-induced deformation.\n- Projected Gradient Estimation describes how the search is approximated.\n",
  "universal-post-training-backdoor-detection": "# Universal Post-Training Backdoor Detection (MM-BD)\n\n## TL;DR {#tldr}\nMM-BD detects a backdoored classifier by searching its pre-softmax logit landscape for a class with an unusually large maximum margin, without assuming the trigger type or using clean samples for detection.\n\n## Intuition {#intuition}\nImagine testing a sealed machine by asking what output it can make when you are allowed to feed it arbitrary inputs. A backdoor target class has learned an unusually reusable route to dominance: many different starting points can be pushed toward a large separation from every competing class. MM-BD treats that geometric oddity as the evidence of compromise.\n\n## Mechanics {#mechanics}\nThe detector has two stages. It estimates one maximum-margin statistic per class with multi-start projected gradient ascent, then tests whether the largest statistic is an outlier under a null distribution fitted from the other classes [§sec_1]. If the p-value is below the fixed significance level, the class owning the largest statistic is reported as the likely target [§sec_1].\n\n## The Math {#the-math}\nFor class $c$, the paper's statistic is $$r_c = \\max_{\\mathbf{x}\\in\\mathcal{X}}\\left[g_c(\\mathbf{x})-\\max_{k\\ne c}g_k(\\mathbf{x})\\right]$$ [§sec_1]. The detector sets $r_{\\max}=\\max_c r_c$ and uses $$p_v = 1-H_0(r_{\\max})^{K-1}$$ [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Backdoor Threat Model explains what the attacker and defender can access.\n- Maximum-Margin Objective derives the statistic used by the detector.\n- Maximum-Margin Backdoor Mitigation (MM-BM) covers the optional repair path.\n",
  "activation-bound-mitigation": "# Maximum-Margin Backdoor Mitigation (MM-BM)\n\n## TL;DR {#tldr}\nMM-BM repairs a detected model by capping layer activations with optimized upper bounds, while trying to preserve clean predictions and leaving the learned weights unchanged.\n\n## Intuition {#intuition}\nA trigger can work because a small set of internal signals becomes unusually large. MM-BM puts a ceiling above every signal: high enough that ordinary examples still pass, but low enough to suppress the extreme activation pattern that carries the backdoor.\n\n## Mechanics {#mechanics}\nThe method applies a separate upper-bound vector to each layer after the first. It optimizes these bounds on a small clean set, constrains clean accuracy to stay above a benchmark, and then applies softmax to the bounded logits [§sec_1]. The paper reports effective mitigation for most tested patterns, with weaker results for very small chessboard perturbations [§sec_1].\n\n## The Math {#the-math}\nFor layer $l$, the bounded activation is $$\\bar{\\sigma}_l(\\mathbf{a};\\mathbf{z}_l)=\\min\\{\\sigma_l(\\mathbf{a}),\\mathbf{z}_l\\}$$ [§sec_1]. The min is componentwise, so $\\mathbf{z}_l$ supplies one ceiling per neuron rather than one global clipping value [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Per-Neuron Activation Upper Bounds gives the architecture-level operation.\n- Accuracy-Preserving Lagrangian gives the optimization objective.\n- Empirical Scope and Failure Modes records the mitigation caveats.\n",
  "pattern-agnostic-signature": "# Pattern-Agnostic Attack Signature\n\n## TL;DR {#tldr}\nThe proposed signature is not the trigger image itself; it is the unusually large target-class margin produced by repeated backdoor features in the trained model.\n\n## Intuition {#intuition}\nDifferent keys can open the same faulty lock. The pixel pattern may be a patch, noise, a blend, or a more advanced construction, but the repeated association can still leave the same kind of geometric scar in the classifier's output surface.\n\n## Mechanics {#mechanics}\nMM-BD avoids reverse-engineering a patch or assuming a perturbation norm. It optimizes the classifier's margin directly, so the input-space embedding mechanism is treated as an unknown nuisance [§sec_1]. The paper argues that even sample-specific triggers can share semantic regularities in latent space, which may preserve detectability [§sec_1].\n\n## The Math {#the-math}\nThe intended separation is $$r_t \\gg r_c\\quad\\text{for non-target }c$$ [§sec_1]. This is a comparative claim about the target statistic among classes, not a guarantee for every attack; the paper explicitly discusses intrinsic backdoors and adaptive attacks as limits [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Trigger-Embedding Families catalogs the explicit image mechanisms used in experiments.\n- Target-Logit Boosting and Non-Target Suppression gives the causal intuition.\n- Adaptive Min-Max Attack shows how an attacker can target the signature.\n",
  "accuracy-preserving-lagrangian": "# Accuracy-Preserving Lagrangian\n\n## TL;DR {#tldr}\nMM-BM minimizes activation-bound norms while penalizing changes between bounded and original logits on a small clean dataset.\n\n## Intuition {#intuition}\nThe repair has a safety contract: shrink the internal dynamic range, but do not change ordinary decisions. A Lagrange multiplier acts like a negotiation knob between stronger suppression and fidelity to the original model.\n\n## Mechanics {#mechanics}\nThe constrained problem requires clean accuracy to exceed a benchmark such as $\\pi=0.95$. The practical algorithm minimizes a logit-matching loss plus a weighted sum of bound norms, adjusting the multiplier when the accuracy constraint is met or violated [§sec_1].\n\n## The Math {#the-math}\nThe paper's constraint is $$\\min_{Z}\\sum_{l=2}^{L}\\|\\mathbf{z}_l\\|_2\\quad\\text{subject to}\\quad \\frac{1}{|D|}\\sum_{(\\mathbf{x},y)\\in D}\\mathbf{1}[y=\\arg\\max_c\\bar g_c(\\mathbf{x};Z)]\\ge\\pi$$ [§sec_1]. Its Lagrangian adds $$\\lambda\\sum_{l=2}^{L}\\|\\mathbf{z}_l\\|_2$$ [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Per-Neuron Activation Upper Bounds describes $Z$.\n- Activation-Bound Mitigation explains why clean samples are needed only here.\n- Maximum-Margin Backdoor Mitigation (MM-BM) summarizes the algorithmic outcome.\n",
  "attacker-capability-ladder": "# Basic, Advanced, and Adaptive Attackers\n\n## TL;DR {#tldr}\nThe paper evaluates increasingly capable attackers, from classical poisoning to attackers who control training and explicitly optimize against MM-BD.\n\n## Intuition {#intuition}\nThink of three adversaries. One can slip notes into the training pile. Another can rehearse with a surrogate model. The strongest knows the detector's test and changes training so the backdoor works while its geometric fingerprint is less obvious.\n\n## Mechanics {#mechanics}\nA basic attacker can poison data but lacks the original training samples and process control. An advanced attacker may gather data or control training. An adaptive attacker has full training control and full knowledge of MM-BD, so it can add a margin-suppressing term to its objective [§sec_1].\n\n## The Math {#the-math}\nThe adaptive setting makes the attacker solve a nested problem of the form $$\\min_{\\phi}\\;L_{\\mathrm{clean}}(\\phi)+L_{\\mathrm{backdoor}}(\\phi)+\\beta_M L_M(t;\\phi)$$ [§sec_1]. The paper defines $L_M$ as the target class's maximum margin, so increasing $\\beta_M$ pressures the attack to hide the detector's signal [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Adaptive Min-Max Attack expands the last rung into an explicit objective.\n- Backdoor Threat Model describes the defender's target.\n- Empirical Scope and Failure Modes summarizes the cost and trade-offs of evasion.\n",
  "adaptive-attack-minimax": "# Adaptive Min-Max Attack\n\n## TL;DR {#tldr}\nAn adaptive attacker can add a penalty on the target maximum margin, but the paper reports a cost in attack success, clean accuracy, optimization time, or some combination.\n\n## Intuition {#intuition}\nThe attacker is trying to keep two things true at once: the trigger must still work, and the detector must no longer see a tall target hill. Flattening the hill while preserving the backdoor turns training into a harder nested optimization problem.\n\n## Mechanics {#mechanics}\nThe adaptive objective adds the target margin to ordinary clean and poisoned cross-entropy training. The paper reports that stronger margin penalties can make attacks undetectable, but also degrade ASR or ACC; a stronger variant that regularizes other classes is even more expensive [§sec_1].\n\n## The Math {#the-math}\nWith model parameters $\\phi$, the adaptive attack includes $$L_M(t;\\phi)=\\max_{\\mathbf{x}\\in\\mathcal{X}}\\left[g_t(\\mathbf{x};\\phi)-\\max_{k\\ne t}g_k(\\mathbf{x};\\phi)\\right]$$ [§sec_1]. The attacker minimizes a weighted sum of clean loss, backdoor loss, and $\\beta_ML_M$ [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Attacker Capability Ladder provides the capability assumptions.\n- Pattern-Agnostic Attack Signature is the quantity being hidden.\n- Empirical Scope and Failure Modes gives the paper's limitation boundary.\n",
  "classical-poisoning-mechanism": "# Classical Poisoning Mechanism\n\n## TL;DR {#tldr}\nA classical backdoor poisons training by embedding a common pattern in source-class samples, relabeling them to a target class, and mixing them into the training set.\n\n## Intuition {#intuition}\nThe attacker teaches the model a second rule: ordinary content maps normally, but the repeated mark overrides that content. Because only a small portion of training data needs the mark, clean behavior can remain apparently intact.\n\n## Mechanics {#mechanics}\nThe paper's classical protocol collects source-class samples, embeds the same pattern, relabels those samples to the target, and inserts them for poisoning [§sec_1]. The trained classifier is evaluated with clean accuracy and attack success rate, so stealth means preserving the first while increasing the second [§sec_1].\n\n## The Math {#the-math}\nFor an additive trigger $\\mathbf{v}$, one image-level abstraction is $$\\tilde{\\mathbf{x}}=[\\mathbf{x}+\\mathbf{v}]_c$$ [§sec_1]. The target behavior can be summarized as $f(\\mathbf{x})=y$ on clean inputs but $f(\\tilde{\\mathbf{x}})=t$ on triggered inputs [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Trigger-Embedding Families compares additive, patch, and blend mechanisms.\n- Backdoor Threat Model places poisoning in the attacker capability ladder.\n- Pattern-Agnostic Attack Signature explains why MM-BD does not reconstruct the poison.\n",
  "clean-data-free-estimation": "# Clean-Data-Free Estimation\n\n## TL;DR {#tldr}\nDetection does not need legitimate images: it generates random valid inputs and optimizes the inspected classifier's logits directly.\n\n## Intuition {#intuition}\nA conventional inspector compares a suspicious model with trusted examples. MM-BD instead asks the model to reveal its own strongest class separation, using random probes as starting points rather than semantic samples.\n\n## Mechanics {#mechanics}\nFor each class, the detector initializes inputs randomly inside the valid domain, performs projected gradient ascent on the margin, and retains the largest local solution across starts [§sec_1]. The paper emphasizes that this avoids the clean-sample requirement of many reverse-engineering detectors [§sec_1].\n\n## The Math {#the-math}\nThe optimization uses only $g_c$ and $\\mathcal{X}$: $$r_c=\\max_{\\mathbf{x}\\in\\mathcal{X}}m_c(\\mathbf{x})$$ [§sec_1]. The clean set $D$ is absent from this expression; it enters only the separate MM-BM mitigation constraint [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Post-Training Defender Constraints defines the information boundary.\n- Projected Gradient Estimation explains the random-probe solver.\n- Unsupervised Anomaly Inference explains why labels are unnecessary.\n",
  "null-margin-distribution": "# Null Distribution of Class Margins\n\n## TL;DR {#tldr}\nThe detector fits a one-sided null distribution to the class margins other than the largest candidate outlier.\n\n## Intuition {#intuition}\nIf one score is suspiciously high, do not let it teach the reference distribution what normal looks like. MM-BD removes the maximum, then uses the remaining scores as its empirical picture of ordinary class separations.\n\n## Mechanics {#mechanics}\nLet $r_{\\max}$ be the largest class statistic. MM-BD estimates $H_0$ from the other $K-1$ values and uses a positive-support density such as a Gamma distribution [§sec_1]. This is an unsupervised reference, not a bank of clean models or labeled attack examples [§sec_1].\n\n## The Math {#the-math}\nThe null fit is evaluated at $r_{\\max}$ through its cumulative distribution: $$H_0(r_{\\max})=\\Pr_{H_0}(R\\le r_{\\max})$$ [§sec_1]. Larger values of the maximum make $1-H_0(r_{\\max})^{K-1}$ smaller, which increases evidence for an attack [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Unsupervised Anomaly Inference puts the fit into the full decision rule.\n- Order-Statistic p-Value explains the multiple-class correction.\n- Empirical Scope and Failure Modes describes small-class-count effects.\n",
  "unsupervised-anomaly-inference": "# Unsupervised Anomaly Inference\n\n## TL;DR {#tldr}\nMM-BD declares an attack when the largest class margin is too atypical under a one-sided null fit to the remaining class margins.\n\n## Intuition {#intuition}\nSuppose a panel of thermometers contains one reading far above the rest. You do not need a labeled example of a faulty thermometer to ask whether that maximum is plausible under the distribution of the other readings.\n\n## Mechanics {#mechanics}\nAfter computing all $r_c$, the method selects $r_{\\max}$ and fits $H_0$ using the other $K-1$ statistics. The paper uses a one-sided density such as a Gamma distribution because the estimated margins are positive [§sec_1]. A detection is made when the order-statistic p-value is below $\\theta$, with $\\theta=0.05$ in the experiments [§sec_1].\n\n## The Math {#the-math}\nThe p-value is $$p_v=1-H_0(r_{\\max})^{K-1}$$ [§sec_1]. Under the no-attack null, the paper states that this order-statistic p-value is uniform on $[0,1]$, so the nominal detection confidence is $1-\\theta$ when $p_v<\\theta$ [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Null Distribution of Class Margins details the leave-one-out fit.\n- Order-Statistic p-Value explains the exponent $K-1$.\n- Empirical Scope and Failure Modes covers false positives and class imbalance.\n",
  "empirical-scope-and-limitations": "# Empirical Scope and Failure Modes\n\n## TL;DR {#tldr}\nThe paper evaluates MM-BD across four image datasets and additional speech and point-cloud settings, while documenting false positives, intrinsic backdoors, and adaptive evasion limits.\n\n## Intuition {#intuition}\nA detector can be strong in its intended regime and still have honest blind spots. Here the important question is not only whether the method works on standard poisoned models, but also whether clean training quirks or a determined attacker can produce the same signature.\n\n## Mechanics {#mechanics}\nThe main experiments cover CIFAR-10, CIFAR-100, TinyImageNet, and GTSRB with additive, patch, and blended patterns, and compare against NC, TABOR, ABS, PT-RED, META, and TND [§sec_1]. The paper reports broadly pattern-invariant detection, but point-cloud performance is weaker in the presence of intrinsic backdoors; class imbalance and deliberately margin-regularized clean models can cause false positives [§sec_1].\n\n## The Math {#the-math}\nThe nominal false-positive control uses $\\theta=0.05$, but the paper notes that estimating $H_0$ from few classes can make observed rates differ from the nominal level [§sec_1]. For adaptive attacks, lowering the target margin can be expressed as an extra term in the attacker objective, creating a direct detector-versus-attacker trade-off [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Adaptive Min-Max Attack details the strongest evasion experiment.\n- Order-Statistic p-Value explains why class count affects calibration.\n- Maximum-Margin Backdoor Mitigation (MM-BM) covers the separate repair results.\n",
  "order-statistic-pvalue": "# Order-Statistic p-Value\n\n## TL;DR {#tldr}\nThe p-value corrects for selecting the largest among K class statistics, then compares the result with a significance threshold.\n\n## Intuition {#intuition}\nLooking at the tallest building in a city is more surprising when the city has only five buildings than when it has thousands. The exponent in the p-value accounts for the fact that MM-BD deliberately searches across all classes for the maximum.\n\n## Mechanics {#mechanics}\nThe paper computes the largest statistic, estimates the null from the remaining statistics, and forms an order-statistic p-value [§sec_1]. With $\\theta=0.05$, it reports an attack when $p_v<\\theta$ and assigns the target label to the class that produced $r_{\\max}$ [§sec_1].\n\n## The Math {#the-math}\nFor $K=|\\mathcal{Y}|$, the paper uses $$p_v=1-H_0(r_{\\max})^{K-1}$$ [§sec_1]. The associated detection confidence is $1-\\theta$ when the p-value falls below $\\theta$ [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Null Distribution of Class Margins supplies $H_0$.\n- Unsupervised Anomaly Inference explains the threshold decision.\n- Empirical Scope and Failure Modes records the nominal-versus-observed false-positive issue.\n",
  "per-neuron-upper-bounds": "# Per-Neuron Activation Upper Bounds\n\n## TL;DR {#tldr}\nMM-BM introduces a separate ceiling for every neuron in selected layers, suppressing abnormally large activations without pruning neurons or changing learned parameters.\n\n## Intuition {#intuition}\nA single dimmer switch would be too crude: some neurons naturally need high values while others carry the suspicious burst. Per-neuron ceilings let the repair tighten each channel independently.\n\n## Mechanics {#mechanics}\nThe bounded network keeps the original layer functions and parameters but replaces each activation with its componentwise minimum against a bound vector [§sec_1]. The paper initializes bounds large enough to avoid initial saturation, then optimizes them downward while monitoring clean accuracy [§sec_1].\n\n## The Math {#the-math}\nFor layers $l=2,\\ldots,L$, the bound vectors are $\\mathbf{z}_l$. The bounded logit is formed by composing clipped layers, with $$\\bar{\\sigma}_l(\\mathbf{a};\\mathbf{z}_l)=\\min\\{\\sigma_l(\\mathbf{a}),\\mathbf{z}_l\\}$$ [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Activation-Bound Mitigation connects ceilings to the full repair.\n- Accuracy-Preserving Lagrangian explains how ceilings are chosen.\n- Empirical Scope and Failure Modes notes why tiny global perturbations are harder to suppress.\n",
  "projected-gradient-estimation": "# Projected Gradient Estimation\n\n## TL;DR {#tldr}\nMM-BD approximates each maximum margin with gradient ascent from multiple random initializations, projecting every iterate back into the valid input set.\n\n## Intuition {#intuition}\nFinding the highest hill in a complicated landscape depends on where you start. Multiple starts give the search several chances, while projection keeps the synthetic probe inside the image domain rather than letting it become an invalid input.\n\n## Mechanics {#mechanics}\nFor each class, the method runs gradient ascent on the margin objective, uses a convergence criterion, and takes the largest local optimum from 30 random initializations in the main experiments [§sec_1]. Projection is appropriate for domains such as pixel boxes, where valid inputs form a closed convex set [§sec_1].\n\n## The Math {#the-math}\nA projected update can be written schematically as $$\\mathbf{x}^{(s+1)}=\\Pi_{\\mathcal{X}}\\left(\\mathbf{x}^{(s)}+\\eta\\nabla_{\\mathbf{x}}m_c(\\mathbf{x}^{(s)})\\right)$$ [§sec_1]. The projection $\\Pi_{\\mathcal{X}}$ enforces the domain constraint while $\\eta$ is the ascent step size [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Maximum-Margin Objective defines the function being optimized.\n- Clean-Data-Free Estimation explains why starts need not be clean examples.\n- Order-Statistic p-Value consumes the final per-class maxima.\n",
  "boosting-and-suppression": "# Target-Logit Boosting and Non-Target Suppression\n\n## TL;DR {#tldr}\nRepeated backdoor features can both boost the target logit and suppress competing logits, producing the margin anomaly MM-BD measures.\n\n## Intuition {#intuition}\nA backdoor is not merely a louder target class. It can also make the alternatives quieter when the model sees the feature combination associated with the poison. The margin captures both effects in one comparison.\n\n## Mechanics {#mechanics}\nThe paper attributes the abnormal target margin to overfitting on a common poisoned feature. It contrasts this with ordinary class-discriminating features, which vary across examples and therefore do not create the same reusable direction [§sec_1]. The appendix shows why maximizing only a target logit can create false detections when semantically neighboring classes rise together [§sec_1].\n\n## The Math {#the-math}\nFor a target $t$, the relevant contrast is $$g_t(\\mathbf{x})-\\max_{k\\ne t}g_k(\\mathbf{x})$$ [§sec_1]. In the paper's linearized argument, confident clean and triggered classifications imply a target-versus-source response to the trigger of at least $2\\tau$ under the stated assumptions [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Pre-Softmax Logit Landscape provides the geometric view.\n- Maximum-Margin Objective formalizes the two-sided comparison.\n- Empirical Scope and Failure Modes notes intrinsic backdoors that can mimic this effect.\n",
  "trigger-embedding-families": "# Trigger-Embedding Families\n\n## TL;DR {#tldr}\nThe experiments include additive patterns, patch replacement patterns, and blended patterns, while MM-BD uses none of these mechanisms as a detection assumption.\n\n## Intuition {#intuition}\nA trigger may be a faint watermark, a small pasted object, or a transparent overlay. A detector tied to one visual recipe can miss the others; MM-BD instead looks for the model-side consequence shared by their repeated use.\n\n## Mechanics {#mechanics}\nThe paper describes additive perturbations, local patch replacement, and blending with a mask and factor. Its experiments also include chessboard, 1-pixel, BadNet, unicolor, and blend variants [§sec_1]. The detector optimizes over images directly, so it need not decide which embedding family generated a suspicious model [§sec_1].\n\n## The Math {#the-math}\nThe patch abstraction is $$\\tilde{\\mathbf{x}}=(1-\\mathbf{m})\\odot\\mathbf{x}+\\mathbf{m}\\odot\\mathbf{u}$$ [§sec_1]. A blended pattern is represented as $$\\tilde{\\mathbf{x}}=(1-\\alpha\\mathbf{m})\\odot\\mathbf{x}+\\alpha\\mathbf{m}\\odot\\mathbf{u}$$ [§sec_1].\n\n## Go Deeper {#go-deeper}\n- Pattern-Agnostic Attack Signature explains the invariant MM-BD uses.\n- Classical Poisoning Mechanism explains how any family becomes training evidence.\n- Empirical Scope and Failure Modes reports cross-pattern performance.\n"
 },
 "notes": {},
 "hotspots": [],
 "clusters": [
  {
   "id": "backdoor-threat-model",
   "label": "Backdoor Threat Model",
   "nodeIds": [
    "attacker-capability-ladder",
    "backdoor-threat-model",
    "classical-poisoning-mechanism",
    "trigger-embedding-families"
   ]
  },
  {
   "id": "post-training-defender-constraints",
   "label": "Post-Training Defender Constraints",
   "nodeIds": [
    "post-training-defender-constraints"
   ]
  },
  {
   "id": "logit-output-landscape",
   "label": "Pre-Softmax Logit Landscape",
   "nodeIds": [
    "logit-output-landscape"
   ]
  },
  {
   "id": "pattern-agnostic-signature",
   "label": "Pattern-Agnostic Attack Signature",
   "nodeIds": [
    "boosting-and-suppression",
    "pattern-agnostic-signature"
   ]
  },
  {
   "id": "maximum-margin-objective",
   "label": "Maximum-Margin Objective",
   "nodeIds": [
    "maximum-margin-objective",
    "projected-gradient-estimation"
   ]
  },
  {
   "id": "unsupervised-anomaly-inference",
   "label": "Unsupervised Anomaly Inference",
   "nodeIds": [
    "order-statistic-pvalue",
    "unsupervised-anomaly-inference"
   ]
  },
  {
   "id": "activation-bound-mitigation",
   "label": "Maximum-Margin Backdoor Mitigation (MM-BM)",
   "nodeIds": [
    "accuracy-preserving-lagrangian",
    "activation-bound-mitigation",
    "per-neuron-upper-bounds"
   ]
  }
 ],
 "tour": [
  {
   "order": 1,
   "title": "Backdoor Threat Model",
   "description": "The paper studies a trained image classifier that behaves normally on clean inputs but routes triggered inputs from one or more source classes to an attacker-chosen target class.",
   "nodeIds": [
    "backdoor-threat-model"
   ]
  },
  {
   "order": 2,
   "title": "Maximum-Margin Objective",
   "description": "For every class, MM-BD maximizes the gap between that class's logit and the largest competing logit over valid inputs.",
   "nodeIds": [
    "maximum-margin-objective"
   ]
  },
  {
   "order": 3,
   "title": "Post-Training Defender Constraints",
   "description": "MM-BD is designed for a downstream user who has the trained classifier but no training set, no known trigger, and no clean reference classifier.",
   "nodeIds": [
    "post-training-defender-constraints"
   ]
  },
  {
   "order": 4,
   "title": "Pre-Softmax Logit Landscape",
   "description": "The logit landscape is the set of class score functions before softmax; MM-BD searches this landscape because a backdoor changes its geometry before probabilities are normalized.",
   "nodeIds": [
    "logit-output-landscape"
   ]
  },
  {
   "order": 5,
   "title": "Universal Post-Training Backdoor Detection (MM-BD)",
   "description": "MM-BD detects a backdoored classifier by searching its pre-softmax logit landscape for a class with an unusually large maximum margin, without assuming the trigger type or using c…",
   "nodeIds": [
    "universal-post-training-backdoor-detection"
   ]
  }
 ],
 "provenance": {
  "path": "pdf",
  "equation_fidelity": "absent"
 },
 "centrality": {
  "universal-post-training-backdoor-detection": 0.0,
  "backdoor-threat-model": 0.0117,
  "post-training-defender-constraints": 0.0,
  "logit-output-landscape": 0.0058,
  "pattern-agnostic-signature": 0.0058,
  "maximum-margin-objective": 0.0117,
  "unsupervised-anomaly-inference": 0.0058,
  "activation-bound-mitigation": 0.0058,
  "classical-poisoning-mechanism": 0.0,
  "trigger-embedding-families": 0.0,
  "attacker-capability-ladder": 0.0058,
  "clean-data-free-estimation": 0.0,
  "boosting-and-suppression": 0.0,
  "projected-gradient-estimation": 0.0,
  "null-margin-distribution": 0.0,
  "order-statistic-pvalue": 0.0,
  "adaptive-attack-minimax": 0.0,
  "per-neuron-upper-bounds": 0.0,
  "accuracy-preserving-lagrangian": 0.0,
  "empirical-scope-and-limitations": 0.0
 },
 "eqIndex": {},
 "trace": [
  {
   "nodeId": "accuracy-preserving-lagrangian",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "activation-bound-mitigation",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "adaptive-attack-minimax",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "attacker-capability-ladder",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "backdoor-threat-model",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "boosting-and-suppression",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "classical-poisoning-mechanism",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "clean-data-free-estimation",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "empirical-scope-and-limitations",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "logit-output-landscape",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "maximum-margin-objective",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "null-margin-distribution",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "order-statistic-pvalue",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "pattern-agnostic-signature",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "per-neuron-upper-bounds",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "post-training-defender-constraints",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "projected-gradient-estimation",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "trigger-embedding-families",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "universal-post-training-backdoor-detection",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  },
  {
   "nodeId": "unsupervised-anomaly-inference",
   "phase": "written",
   "status": "ok",
   "date": "2026-07-17"
  }
 ],
 "glossary": {},
 "excerpts": {},
 "dependentSide": {
  "part-of": "dst",
  "prerequisite": "dst",
  "builds-on": "src"
 }
};
