import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from build_data import (build_bundle, reading_path, strip_images,
                        to_data_ts)

FIXTURE = json.loads((Path(__file__).resolve().parents[2] / "fixtures" /
                      "aiayn_concept_graph.json")
                     .read_text(encoding="utf-8"))
PACK = {"meta": {"source": "arXiv:1706.03762", "title": "AIAYN",
                 "generated": "2026-07-09"},
        "extraction": {"path": "latex", "equation_fidelity": "exact"},
        "sections": [{"id": "sec_3_2", "title": "SDPA", "level": 2, "text": "t"}],
        "equations": [{"id": "eq_1", "latex": "x", "section": "sec_3_2"}],
        "references": [], "figures": []}


def test_bundle_has_all_contract_keys():
    b = build_bundle(FIXTURE, pack=PACK)
    for k in ("meta", "nodes", "edges", "pages", "notes", "hotspots",
              "clusters", "tour", "provenance", "centrality", "eqIndex",
              "trace", "glossary"):
        assert k in b, k


def test_tour_is_deterministic_reading_path_head():
    b = build_bundle(FIXTURE, pack=PACK)
    order = reading_path(FIXTURE)
    assert [s["nodeIds"][0] for s in b["tour"]] == order[:5]
    assert all(s["title"] and s["description"] for s in b["tour"])


def test_clusters_fall_back_to_level1_grouping():
    b = build_bundle(FIXTURE, pack=PACK)
    ids = {c["id"] for c in b["clusters"]}
    assert "attention" in ids
    members = next(c for c in b["clusters"] if c["id"] == "attention")["nodeIds"]
    assert "scaled-dot-product-attention" in members


def test_centrality_present_for_every_node():
    b = build_bundle(FIXTURE, pack=PACK)
    assert set(b["centrality"]) == {n["id"] for n in FIXTURE["nodes"]}


def test_eq_index_maps_equation_to_anchored_concepts():
    g = json.loads(json.dumps(FIXTURE))
    g["nodes"][0]["source_ref"] = "sec_3_2"
    b = build_bundle(g, pack=PACK)
    assert g["nodes"][0]["id"] in b["eqIndex"]["eq_1"]


def test_strip_images_removes_and_counts():
    md = "before ![diagram](../assets/x.png) after"
    out, n = strip_images(md)
    assert "![" not in out and "x.png" not in out and n == 1


def test_ts_output_is_wellformed_and_unicode_raw(tmp_path):
    b = build_bundle(FIXTURE, pack=PACK)
    ts = to_data_ts(b)
    assert ts.startswith("// generated by build_data.py")
    assert "export const KE_DATA" in ts
    assert "√dₖ" in ts
    json.loads(ts.split("=", 1)[1].rstrip().rstrip(";"))
