import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from build_data import (build_bundle, main, reading_path, strip_images,
                        to_data_ts)

ROOT = Path(__file__).resolve().parents[2]
FIXTURE_PATH = ROOT / "fixtures" / "aiayn_concept_graph.json"
COMMITTED_DATA = ROOT / "dashboard" / "src" / "data.gen.ts"
FIXTURE = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
PACK = {"meta": {"source": "arXiv:1706.03762", "title": "AIAYN",
                 "generated": "2026-07-09"},
        "extraction": {"path": "latex", "equation_fidelity": "exact"},
        "sections": [{"id": "sec_3_2", "title": "SDPA", "level": 2, "text": "t"}],
        "equations": [{"id": "eq_1", "latex": "x", "section": "sec_3_2"}],
        "references": [], "figures": []}


def test_bundle_has_all_contract_keys():
    b = build_bundle(FIXTURE, pack=PACK)
    for k in ("meta", "nodes", "edges", "pages", "notes", "hotspots",
              "clusters", "tour", "provenance", "centrality", "eqIndex",
              "trace", "glossary"):
        assert k in b, k


def test_dependent_side_matches_edge_direction_contract():
    assert build_bundle(FIXTURE, pack=PACK)["dependentSide"] == {
        "part-of": "dst",
        "prerequisite": "dst",
        "builds-on": "src",
    }


def test_tour_is_deterministic_reading_path_head():
    b = build_bundle(FIXTURE, pack=PACK)
    order = reading_path(FIXTURE)
    assert [s["nodeIds"][0] for s in b["tour"]] == order[:5]
    assert all(s["title"] and s["description"] for s in b["tour"])


def test_clusters_fall_back_to_level1_grouping():
    b = build_bundle(FIXTURE, pack=PACK)
    ids = {c["id"] for c in b["clusters"]}
    assert "attention" in ids
    members = next(c for c in b["clusters"] if c["id"] == "attention")["nodeIds"]
    assert "scaled-dot-product-attention" in members


def test_centrality_present_for_every_node():
    b = build_bundle(FIXTURE, pack=PACK)
    assert set(b["centrality"]) == {n["id"] for n in FIXTURE["nodes"]}


def test_eq_index_maps_equation_to_anchored_concepts():
    g = json.loads(json.dumps(FIXTURE))
    g["nodes"][0]["source_ref"] = "sec_3_2"
    b = build_bundle(g, pack=PACK)
    assert g["nodes"][0]["id"] in b["eqIndex"]["eq_1"]


def test_strip_images_removes_and_counts():
    md = "before ![diagram](../assets/x.png) after"
    out, n = strip_images(md)
    assert "![" not in out and "x.png" not in out and n == 1


def test_note_trace_dates_are_content_based_and_mtime_stable(tmp_path):
    pages_dir = tmp_path / "pages"
    wiki_dir = tmp_path / "wiki"
    pages_dir.mkdir()
    wiki_dir.mkdir()
    (pages_dir / "01_attention.md").write_text(
        "before ![diagram](../assets/x.png) after", encoding="utf-8")
    notes = {
        "attention.yaml": (
            'concept: attention\nstatus: verified\ndate: "2024-01-02"\n'
            'generated: "2024-01-01"\nsynthesis: dated\n'),
        "encoder-decoder-stack.yaml": (
            'concept: encoder-decoder-stack\nstatus: verified\n'
            'generated: "2024-02-03"\nsynthesis: generated\n'),
        "positional-encoding.yaml": (
            'concept: positional-encoding\nstatus: verified\n'
            'synthesis: fallback\n'),
    }
    for name, content in notes.items():
        path = wiki_dir / name
        path.write_text(content, encoding="utf-8")
        os.utime(path, (946684800, 946684800))

    first = build_bundle(FIXTURE, pages_dir=pages_dir, wiki_dir=wiki_dir)
    for path in wiki_dir.glob("*.yaml"):
        os.utime(path, (1893456000, 1893456000))
    second = build_bundle(FIXTURE, pages_dir=pages_dir, wiki_dir=wiki_dir)

    assert first == second
    researched_dates = {
        item["nodeId"]: item["date"]
        for item in first["trace"] if item["phase"] == "researched"
    }
    assert researched_dates == {
        "attention": "2024-01-02",
        "encoder-decoder-stack": "2024-02-03",
        "positional-encoding": FIXTURE["meta"]["generated"],
    }
    assert first["pages"]["attention"] == "before  after"
    assert {item["date"] for item in first["trace"]
            if item["phase"] == "written"} == {FIXTURE["meta"]["generated"]}


def test_ts_output_is_wellformed_and_unicode_raw():
    b = build_bundle(FIXTURE, pack=PACK)
    ts = to_data_ts(b)
    assert ts.startswith("// generated by build_data.py")
    assert "export const KE_DATA" in ts
    assert "√dₖ" in ts
    json.loads(ts.split("=", 1)[1].rstrip().rstrip(";"))


def test_cli_writes_utf8_with_byte_stable_lf(tmp_path):
    out = tmp_path / "data.gen.ts"

    assert main(["--graph", str(FIXTURE_PATH), "--out", str(out)]) == 0

    data = out.read_bytes()
    assert data.startswith(b"// generated by build_data.py")
    assert b"\r\n" not in data
    assert data.endswith(b";\n")
    assert "√dₖ".encode() in data


def test_repo_fixture_regeneration_matches_committed_data(tmp_path):
    out = tmp_path / "data.gen.ts"

    assert main(["--graph", str(FIXTURE_PATH), "--out", str(out)]) == 0

    assert (out.read_text(encoding="utf-8") ==
            COMMITTED_DATA.read_text(encoding="utf-8"))
